### ISSUE TITLE
Constructor Cannot Be Invoked - Babel

### ISSUE THREAD

**Issue by jdachenhaus** [jdachenhaus/lm-bot#1]
After compiling using babel command preset the following issue was presented:

```cmd
C:\Users\Jacob\Documents\GitHub\loremasterbot\lib\classes.js:52
    _this = _possibleConstructorReturn(this, _getPrototypeOf(LMBClient).call(this, options));
                                                                        ^

TypeError: Class constructor Client cannot be invoked without 'new'
    at new LMBClient (C:\Users\Jacob\Documents\GitHub\loremasterbot\lib\classes.js:52:73)
    at Object.<anonymous> (C:\Users\Jacob\Documents\GitHub\loremasterbot\lib\index.js:9:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

I believe this is an issue with the babel configuration, but will require further review and code inspection. Will be working on this issue as soon as possible.

**Comment by jdachenhaus** [comment]
Fixed in [1b73034](https://github.com/jdachenhaus/lm-bot/commit/1b73034a075839ebdfe7667816f3a9ea8948c078). Removed Babel from the dependencies as it was not longer required.
